// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYoCcP3DmID4houg6SFe5CgU4DYLIbdWE',
    appId: '1:435711528319:web:7f3b736161cf5461775e4a',
    messagingSenderId: '435711528319',
    projectId: 'todo-app-de6f8',
    authDomain: 'todo-app-de6f8.firebaseapp.com',
    storageBucket: 'todo-app-de6f8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjVuxgvvikKNo0mriOtg4L-8z_4rRQ-VA',
    appId: '1:435711528319:android:2c3609040133ea59775e4a',
    messagingSenderId: '435711528319',
    projectId: 'todo-app-de6f8',
    storageBucket: 'todo-app-de6f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu6XBESCeRfSmbhuMzJCeUy7TGe25vX6U',
    appId: '1:435711528319:ios:0c5f419b2d89fca8775e4a',
    messagingSenderId: '435711528319',
    projectId: 'todo-app-de6f8',
    storageBucket: 'todo-app-de6f8.appspot.com',
    iosBundleId: 'com.example.brandAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu6XBESCeRfSmbhuMzJCeUy7TGe25vX6U',
    appId: '1:435711528319:ios:c8b58a7656717152775e4a',
    messagingSenderId: '435711528319',
    projectId: 'todo-app-de6f8',
    storageBucket: 'todo-app-de6f8.appspot.com',
    iosBundleId: 'com.example.brandAssignment.RunnerTests',
  );
}
